import os, osproc, strformat, strutils, times

const
  bootstrapScriptName = "bootstrap-step-ca.sh"
  defaultConfigPath = "/etc/step-ca"

let timestamp = now().format("yyyy-MM-dd HH:mm:ss")

# Adjust as needed
let stepCaPath = findExe("step-ca")
if stepCaPath.len == 0:
  stderr.writeLine("[ERR] 'step-ca' binary not found in PATH. Aborting.")
  quit(1)

let bootstrapScript = &"""
#!/bin/bash
# Generated by rezn-seedr on {timestamp}
set -euo pipefail

echo "[INFO] Creating step user..."
id -u step &>/dev/null || useradd --user-group --system --home {defaultConfigPath} --shell /bin/false step

echo "[INFO] Granting CAP_NET_BIND_SERVICE to step-ca..."
setcap CAP_NET_BIND_SERVICE=+eip "{stepCaPath}"

echo "[INFO] Preparing CA config directory..."
mkdir -p {defaultConfigPath}
cp -r ./ca-config/* {defaultConfigPath}/

echo "[INFO] Updating ownership..."
chown -R step:step {defaultConfigPath}

echo "[INFO] Creating systemd unit..."
cat > /etc/systemd/system/step-ca.service <<EOF
[Unit]
Description=step-ca
After=network.target

[Service]
Type=simple
User=step
ExecStart={stepCaPath} {defaultConfigPath}/config/ca.json
WorkingDirectory={defaultConfigPath}
Restart=always

[Install]
WantedBy=multi-user.target
EOF

echo "[INFO] Reloading systemd daemon and enabling step-ca..."
systemctl daemon-reexec
systemctl daemon-reload
systemctl enable --now step-ca

echo "[SUCCESS] step-ca is up and running!"
"""

# Save the script to disk
try:
  writeFile(bootstrapScriptName, bootstrapScript)
  discard execShellCmd("chmod +x " & bootstrapScriptName)
  let hash = execProcess("sha256sum " & bootstrapScriptName).split()[0]
  echo &"""
[OK] Bootstrap script generated: ./{bootstrapScriptName}
     SHA256: {hash}
Run it with:

  sudo ./{bootstrapScriptName}
"""
except IOError as e:
  stderr.writeLine("[ERR] Failed to write bootstrap script: " & e.msg)
  quit(1)
